# Intervalle de polling (secondes)
INTERVAL=10

# Plex
PLEX_IP=YOUR_PLEX_IP
PLEX_PORT=32400
PLEX_TOKEN=YOUR_PLEX_TOKEN

# WATCHDIRS
# format :
# chemin_local | plex_lib_id | label | chemin_plex (base)
# Le chemin envoyé à Plex sera : chemin_plex + sous-dossiers
WATCHDIRS="
/mnt/decypharr/shows/torrents|2|series|/decypharr/shows/torrents
/mnt/decypharr/movies/torrents|1|films|/decypharr/movies/__all__
"
